spring.application.name=cloudvault

# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5433/cloudvault
spring.datasource.username=mrugeshpatil
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# File Upload
# =========================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================
# Server
# =========================
server.port=8080

# =========================
# MinIO
# =========================
minio.url=http://127.0.0.1:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucket=cloudvault

# =========================
# Ollama
# =========================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3:8b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.think=false

spring.ai.ollama.chat.options.max-tokens=300

spring.ai.ollama.chat.options.num-ctx=4096
spring.ai.ollama.chat.options.keep-alive=30m

spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.embedding.options.keep-alive=30m

# turn off the SQL and debug noise while benchmarking
# =========================
# Spring AI - PGVector
# =========================

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768



# =========================
# Logging
# =========================
logging.level.com.cloudvault=DEBUG

# =========================
# App
# =========================
app.base-url=http://localhost:8080
app.dedup-key=gIsJj8TRv8i24NNz5l9PJexOqI/HFImlT3EwuiP9lA0=