spring.application.name=cloudvault
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudvault
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=8080

minio.url=http://127.0.0.1:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucket=cloudvault

# Ensure logging is enabled so we can see the parallel chunking in action
logging.level.com.cloudvault=DEBUG


app.base-url=http://localhost:8080
app.dedup-key=gIsJj8TRv8i24NNz5l9PJexOqI/HFImlT3EwuiP9lA0=